version: 2.1
orbs:
  node: circleci/node@5.0.1
  docker: circleci/docker@2.1.4
  snyk: snyk/snyk@1.5.0

jobs:
  build:
    docker:
      - image: cimg/node:22.19
    steps:
      - checkout

      - node/install-packages:
          pkg-manager: npm

  test:
    docker:
      - image: cimg/node:22.19
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: |
          echo "Running tests..."
          npm run test -- --run

  scan:
    docker:
      - image: cimg/node:16.10
    environment:
      IMAGE_NAME: nzj002/node-app-test-repository
    steps:
      - checkout
      - setup_remote_docker
      - docker/check:
          docker-username: DOCKER_LOGIN
          docker-password: DOCKER_PASSWORD
      - run: docker build -t $DOCKER_IMAGE .
      - snyk/scan:
          docker-image-name: $DOCKER_IMAGE
          fail-on-issues: false
          severity-threshold: medium
  publish:
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/check:
          docker-username: DOCKER_LOGIN
          docker-password: DOCKER_PASSWORD
      - docker/build:
          image: $DOCKER_IMAGE
          tag: << pipeline.git.revision >>,latest
      - docker/push:
          image: $DOCKER_IMAGE
          tag: << pipeline.git.revision >>,latest

workflows:
  simple_workflow:
    jobs:
      - build
      - test:
          requires:
            - build
      - scan:
          requires:
            - build
      - publish:
          requires:
            - test
